#!/bin/env ruby
# Helper program to help define constants
# 
class Defconst
  def main(argv)
    infile    = argv[0]
    classname = argv[1]
    unless infile && classname
      warn "Usage: defconst infile classname"
      return -1
    end
    indata = File.read(infile)
    raise "Couldn not open input file." unless indata
#     outfile = File.open(outname, 'wt') 
#     raise "Couldn not open input file." unless outfile
     
    parts   = indata.split(/[;,]/).map { |e| e.gsub(/[\n\r ]/,'') }
    okparts = parts.select { |p| p =~ /=/ }
    to_export = []
    puts "/** This file was autogenerated from #{infile} */"
    okparts.each do |p| 
      m = p.match(/ALLEGRO_[A-Z0-9_]+/)
      if m
        alname = m[0] 
        rbname = alname.gsub(/ALLEGRO_/,'');
        puts(
        "  rb_define_const(#{classname}, \"#{rbname}\", UINT2NUM(#{alname}));")
      end    
    end 
   
  end
end
  
  
Defconst.new.main(ARGV)  






