#include "ralleg5.h"


static VALUE cKeyboardState;


static VALUE cKey;

static VALUE cKeyboard;

VALUE rbal_keyboard_init(VALUE rself) {
  return RBH_INT_BOOL(al_install_keyboard());
}
   
VALUE rbal_keyboard_init_p(VALUE rself) {
  return RBH_INT_BOOL(al_is_keyboard_installed());
}
   
VALUE rbal_keyboard_done(VALUE rself) {
  al_uninstall_keyboard();
  return rself;
}

VALUE rbal_keyboard_setleds(VALUE rself, VALUE rleds) {
  return RBH_INT_BOOL(al_set_keyboard_leds(RBH_INT(rleds)));
}

VALUE rbal_keyboard_down_p(VALUE rself, VALUE rkeycode) {
  ALLEGRO_KEYBOARD_STATE state;
  int keycode = RBH_INT(rkeycode);
  al_get_keyboard_state(&state);
  if (keycode > ALLEGRO_KEY_MAX) return Qnil;
  if (keycode < 0) return Qnil;
  return RBH_INT_BOOL(al_key_down(&state, keycode));
}

VALUE rbal_keyboard_keyname(VALUE rself, VALUE rkeycode) {
  const char * name = NULL;
  int keycode = RBH_INT(rkeycode);
  if (keycode > ALLEGRO_KEY_MAX) return Qnil;
  if (keycode < 0) return Qnil;
  name = al_keycode_to_name(keycode);
  return RBH_STR_UTF82(name); 
}

VALUE rbal_keyboard_eventsource(VALUE rself) { 
  return rbal_eventsource_wrap_nofree(al_get_keyboard_event_source());
}


/* unused for now */
void ralleg5_keyboardstate_init(VALUE mAl) {
  cKeyboardState = rb_define_class_under(mAl, "KeyboardState" , rb_cObject);  
}  


void ralleg_key_init(VALUE mAl) {
  cKey = rb_define_module_under(mAl, "Key");
  /* I'm lazy here and let the autogenerated file be included. */
  #include "key.inc"
}

void ralleg5_keyboard_init(VALUE mAl) {
  /* ralleg5_keyboardstate_init(mAl); */
  ralleg_key_init(mAl);
  cKeyboard = rb_define_class_under(mAl, "Keyboard"   , rb_cObject);
  rb_define_singleton_method(cKeyboard, "init"    , rbal_keyboard_init   , 0);
  rb_define_singleton_method(cKeyboard, "init?"   , rbal_keyboard_init_p , 0);
  rb_define_singleton_method(cKeyboard, "done"    , rbal_keyboard_done   , 0);
  rb_define_singleton_method(cKeyboard, "setleds" , rbal_keyboard_setleds, 1);
  rb_define_singleton_method(cKeyboard, "keyname" , rbal_keyboard_keyname, 1);
  rb_define_singleton_method(cKeyboard, "down?"   , rbal_keyboard_down_p , 1);
  rb_define_singleton_method(cKeyboard, "eventsource", rbal_keyboard_eventsource, 0);  
    
} 



