#include "ralleg5.h"

static VALUE cMouseState;
static VALUE cMouse;
static VALUE cCursor;

VALUE rbal_mouse_init(VALUE rself) {
  return RBH_INT_BOOL(al_install_mouse());
}
   
VALUE rbal_mouse_init_p(VALUE rself) {
  return RBH_INT_BOOL(al_is_mouse_installed());
}
   
VALUE rbal_mouse_done(VALUE rself) {
  al_uninstall_mouse();
  return rself;
}

VALUE rbal_mouse_buttons(VALUE rself) {  
  return RBH_UINT_NUM(al_get_mouse_num_buttons());
}

VALUE rbal_mouse_axes(VALUE rself) {  
  return RBH_UINT_NUM(al_get_mouse_num_axes());
}

VALUE rbal_mouse_eventsource(VALUE rself) { 
  return rbal_eventsource_wrap_nofree(al_get_mouse_event_source());
}



/*
AL_FUNC(bool,           al_set_mouse_xy,        (struct ALLEGRO_DISPLAY *display, int x, int y));
AL_FUNC(bool,           al_set_mouse_z,         (int z));
AL_FUNC(bool,           al_set_mouse_w,         (int w));
AL_FUNC(bool,           al_set_mouse_axis,      (int axis, int value));
AL_FUNC(void,           al_get_mouse_state,     (ALLEGRO_MOUSE_STATE *ret_state));
AL_FUNC(bool,           al_mouse_button_down,   (const ALLEGRO_MOUSE_STATE *state, int button));
AL_FUNC(int,            al_get_mouse_state_axis, (const ALLEGRO_MOUSE_STATE *state, int axis));

AL_FUNC(ALLEGRO_EVENT_SOURCE *, al_get_mouse_event_source, (void));
*/

/* Also cursor api, later */


void ralleg_cursor_init(VALUE mAl) {
  cCursor = rb_define_module_under(mAl, "Cursor");
  /* I'm lazy here and let the autogenerated file be included. */
  #include "cursor.inc"
}

void ralleg5_mouse_init(VALUE mAl) {
  ralleg_cursor_init(mAl);
  cMouse = rb_define_class_under(mAl, "Mouse"   , rb_cObject);
  rb_define_singleton_method(cMouse, "init"    , rbal_mouse_init   , 0);
  rb_define_singleton_method(cMouse, "init?"   , rbal_mouse_init_p , 0);
  rb_define_singleton_method(cMouse, "done"    , rbal_mouse_done   , 0);
  rb_define_singleton_method(cMouse, "axes"    , rbal_mouse_axes   , 0);
  rb_define_singleton_method(cMouse, "buttons" , rbal_mouse_buttons, 0);
  rb_define_singleton_method(cMouse, "eventsource", rbal_mouse_eventsource, 0);
  

}



